### PR TITLE
Remove default time ordering from xds_from_ms

### PR DESCRIPTION
**Pull request by sjperkins**
- [x] Tests added / passed

  ```bash
  $ py.test -v -s daskms/tests
  ```

  If the pep8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8` and
  `pycodestyle` to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8 pycodestyle
  $ autopep8 -r -i daskms
  $ flake8 daskms
  $ pycodestyle daskms
  ```

- [x] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

### CODE REVIEW

**Comment by sjperkins** [comment]
/cc @JSKenyon @landmanbester @Mulan-94 @o-smirnov @Jordatious @bennahugo @hrkloeck @paoloserra

This PR stops ordering Measurement Sets by TIME as default behaviour, instead reading MS rows in their natural order. The reason for this is that, for MS's that are not monotonically ordered in TIME, non-contiguous row reads will be silently introduced and likely create confusion for the user.

Removing this default ordering means that downstream applications may need to modify their xds_from_ms calls to explicitly specify the index\_cols argument: `xds_from_ms(..., index_cols=["TIME"])`.

Are there any objections to this breaking change targetted for a release in dask-ms 0.2.7? I can imagine this being an issue for applications that require a `TIME` ordering by default (Quartical, perhaps Tricolour). This is probably not an issue for crystalball.

**Comment by sjperkins** [comment]
Note that I will merge this EOD Friday.

**Comment by Jordatious** [comment]
Thanks @sjperkins. Sounds good to me. Does this address the issue Joe Bochenek mentioned?

**Comment by sjperkins** [comment]
@Jordatious By removing the default (TIME), the row ordering will be natural (i.e. as they're laid out on disk), contiguous and performance should be optimal in all cases.

Application owners will now need to explicitly request an ordering if they want one, and will need to deal with any potential non-contiguous row ordering problems.

**Pull request merged**
