### PR TITLE
Data Column Expressions

### PR DESCRIPTION
**Pull request by sjperkins**
- [x] Tests added / passed

  ```bash
  $ py.test -v -s daskms/tests
  ```

  If the pep8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8` and
  `pycodestyle` to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8 pycodestyle
  $ autopep8 -r -i daskms
  $ flake8 daskms
  $ pycodestyle daskms
  ```

- [x] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

### CODE REVIEW

**Comment by sjperkins** [comment]
@o-smirnov @bennahugo @IanHeywood @JSKenyon @smasoka @rubyvanrooyen 

Primarily with https://github.com/ska-sa/tricolour/issues/70 in mind but might be useful elsewhere:

Code snippet:

```python
datasets = xds_from_ms("WSRT.MS")
datasets = data_column_expr("2 * DATA / (DIR1_DATA + DIR2_DATA)", datasets)
consume(datasets[0].DATA_EXPRESSION.data)
```

**Comment by sjperkins** [comment]
and @landmanbester  of course

**Comment by sjperkins** [comment]
Changed to support assignments:

```python
datasets = xds_from_ms("WSRT.MS")
datasets = data_column_expr("EXPR = 2 * DATA / (DIR1_DATA + DIR2_DATA)", datasets)
consume(datasets[0].EXPR.data)
```

**Comment by o-smirnov** [comment]
This is an absolutely awesome change, much more powerful than my simple binary arithmetic. I look forward to supporting this in shadeMS!

**Comment by sjperkins** [comment]
It supports a simple calculator syntax at the moment (no functions), but it could always be expanded later.

**Pull request merged**
